# Site settings
title: Phil Chapavich T.
header-img: img/home-bg.jpg
post-default-header-img: "assets/img/header/news-post-default.jpg"
description: "Phil Chapavich | Film, game, and multimedia composer"
baseurl: ""
url: "http://phil-wc.github.io"

# Build settings
markdown: kramdown
highlighter: rogue
paginate: 6
paginate_path: news/page/:num
gems: ["jekyll-paginate"]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
permalink: pretty


# lazy declaration shit, so don't needed to define front matter every page
author:
  name: "CHAPAVICH TEMNITIKUL"
  artist_name: "phil_wc"

sass:
  sass_dir: _sass

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "page"
      kind: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      kind: "post"
