# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
gems: ["jekyll-paginate"]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]


# lazy declaration shit, so don't needed to define front matter every page
author:
  name: "CHAPAVICH TEMNITIKUL"
  artist_name: "phil_wc"

sass:
  sass_dir: _sass

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
